wip
unyc-io/ntc-templates pull request #33
Opened 2023-01-02 16:00 UTC by guillaume-mbali

**ISSUE TYPE**
New Template Pull Request

**COMPONENT**
ubiquiti_edgerouter_show_interfaces.textfsm, edgerouter, show interfaces

**SUMMARY**
Added the ubiquiti edgerouter template to show eth interfaces

2023-01-19 05:45 UTC, elavaud requested changes
Rename commit. It is for NTC template, not us. Like:
feat(ubiquiti): Add template ubiquiti edgerouter show interfaces

2023-01-19 05:45 UTC, elavaud commented on ntc_templates/templates/ubiquiti_edgerouter_show_interfaces.textfsm
> +Value DESCRIPTION ([\w\d\-]+)
Put DESCRIPTION under LINK_STATUS to maintain order

2023-01-19 05:45 UTC, elavaud commented on ntc_templates/templates/ubiquiti_edgerouter_show_interfaces.textfsm
> +  ^\s+${IPV6_ADDRESS} -> Record
There are way too much possibilities.
You should be able to do something much cleaner with "Continute.record" like in huawei_vrp_display_acl_all
You can use also "Required" to indicate the value need to be collected before recording.

Those 15 lines can be reduced to 3 or 5

You can also check huawei_vrp_display_interface_description for that thing of Starting the recording only after a certain line. You would ensure you would start recording right after
"Interface    IP Address                        S/L  Description "
and you would be able to include the first lines

2023-01-19 05:45 UTC, elavaud commented on tests/ubiquiti_edgerouter/show_interfaces/ubiquiti_edgerouter_show_interfaces.raw
> +             ::1/128
Add 2 dummy interfaces, one with only an IPv4 address, and one with only an IPv6 address.
You could use eth2 and eth3. In that way you would have all cases.

Also, make one Administratively down

2023-01-25 00:11 UTC, elavaud approved these changes
Ok for me.
You can convert to draft, put it on NTC side, add the tags on this PR, and cherry-pick the commit in our v3.1.0 branch

2023-02-16 11:08 UTC, guillaume-mbali commented
Official release : [#1291](https://github.com/networktocode/ntc-templates/pull/1291)

2023-05-15 13:35 UTC, closed without merging